[versions]
activityCompose = "1.12.4"
agp = "9.0.1"
androidxComposeMaterial = "1.5.6"
composeFoundation = "1.5.6"
composeMaterial = "1.5.6"
composeMaterialVersion = "1.5.6"
datastorePreferences = "1.2.0"
horologistComposeLayout = "0.7.15"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleViewmodelCompose = "2.10.0"
lifecycleViewmodelComposeVersion = "2.10.0"
material = "1.13.0"
materialVersion = "1.10.3"
preference = "1.2.1"
foundationLayout = "1.10.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-foundation-v131 = { module = "androidx.wear.compose:compose-foundation", version.ref = "composeFoundation" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-viewmodel-compose-v270 = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "composeMaterial" }
compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeMaterial" }
compose-material-v130 = { module = "androidx.wear.compose:compose-material", version.ref = "composeMaterialVersion" }
compose-material-v131 = { module = "androidx.wear.compose:compose-material", version.ref = "androidxComposeMaterial" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologistComposeLayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

